### PR TITLE
ItemStackBuilder: Add a new generic ItemMeta API

### LINKED ISSUE #33: ItemStackBuilder: Introduce a new ItemMeta API
Remove the deprecated Dye and Skull helpers, and replace them with a new API to handle generic `ItemMeta`.

Since we can use Java 8 lambdas, something like this would be nice:

```java
ItemStack fooSkull = new ItemStackBuilder(Material.PLAYER_HEAD)
  .withMeta((SkullMeta s) -> s.setOwner("foo"))
  .item(); // Now we have a skull item of player foo
```

Where the given lambda is only ran if the resulting `ItemStack` has a matching `ItemMeta`, preventing unexpected exception. The method could be chained several times to allow for either multiple actions on a same item type, or different actions depending on the final built itemStack.

### PR DESCRIPTION
**Pull request by prokopyl**
This adds a new `withMeta()` method to the `ItemStackBuilder`, and removes the `head` and `dye` utilities, as discussed in #33.

I also took the opportunity to remove the internal `arrayToString()` method, replacing it with Java 8 `String.join()`.

Closes #33.

### CODE REVIEW

File: src/main/java/fr/zcraft/quartzlib/tools/items/ItemStackBuilder.java [hunk 1]
```diff
@@ -652,37 +645,6 @@ public ItemStackBuilder data(short data)
...
-     *
-     * @param owner The head's owner, implying the skin displayed on the head.
-     *
-     * @return The current ItemStackBuilder instance, for methods chaining.
-     */
-    public ItemStackBuilder head(String owner)
-    {
-        this.headOwner = owner;
-        return this;
-    }
```
Comment (AmauryCarrade) [inline src/main/java/fr/zcraft/quartzlib/tools/items/ItemStackBuilder.java:684]: What about keeping this as as convenient method to set the material to `PLAYER_HEAD` and the skull meta to the right name?

Something like:

```java
final ItemStack head = new ItemStackBuilder().head("Pileurs").item();
```

File: src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+import org.bukkit.inventory.meta.SkullMeta;
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+import java.util.Objects;
+
+class MojangHeadTest extends MockedBukkitTest {
+    @Test
+    void canCreateHeadItems() {
+        Assertions.assertEquals("MHF_Cake", MojangHead.CAKE.getHeadName());
```
Comment (AmauryCarrade) [inline src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java:15]: We should also test this for composed names, to ensure the names are correctly transformed, and ones with a specified name to ensure it is taken into account.

```suggestion
        Assertions.assertEquals("MHF_Cake", MojangHead.CAKE.getHeadName());
        Assertions.assertEquals("MHF_MushroomCow", MojangHead.MUSHROOM_COW.getHeadName());
        Assertions.assertEquals("MHF_CoconutB", MojangHead.COCONUT_BROWN.getHeadName());
```

File: src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+        Assertions.assertEquals(1, item.getAmount());
+        Assertions.assertEquals("MHF_Cake", ((SkullMeta) Objects.requireNonNull(item.getItemMeta())).getOwner());
+
+        ItemStack isbItem = MojangHead.CAKE.asItemBuilder().item();
+
+        Assertions.assertEquals(Material.PLAYER_HEAD, isbItem.getType());
+        Assertions.assertEquals(1, item.getAmount());
+        Assertions.assertEquals("MHF_Cake", ((SkullMeta) Objects.requireNonNull(isbItem.getItemMeta())).getOwner());
+    }
+}
```
Comment (AmauryCarrade) [inline src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java:28]: Poor new line :(

**Review by AmauryCarrade — COMMENTED** [review]
A few comments but nice overall :)

File: src/main/java/fr/zcraft/quartzlib/tools/items/ItemStackBuilder.java (hunk 1 above)
Comment (prokopyl) [reply src/main/java/fr/zcraft/quartzlib/tools/items/ItemStackBuilder.java:684]: I think we'd want to keep the ItemStackBuilder as generic as possible, without getting involved in any specific Item, because `ItemMeta`s have pretty extensive APIs that we don't want to reproduce all in one place.

The `SkullMeta` API for example, now accepts both a player name and an `OfflinePlayer` (the player name version being actually deprecated), and using this helper doesn't shorten the code all that much. :/

I'm also not convinced heads are used that much more, compared to other items with more complex `ItemMeta`s, at least not enough to warrant an extra specific method.

File: src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java (hunk 2 above)
Comment (prokopyl) [reply src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java:15]: This was just a quick test to cover my changes, but ideally since the MHF heads are a known, fixed list, we should probably test every one of them directly.

Maybe this would be better done in a separate PR however?

File: src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java (hunk 3 above)
Comment (prokopyl) [reply src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java]: Guess that's why we need proper code format checks in CI :p

File: src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java (hunk 2 above)
Comment (AmauryCarrade) [reply src/test/java/fr/zcraft/quartzlib/tools/mojang/MojangHeadTest.java:15]: Yes and yes.

File: src/main/java/fr/zcraft/quartzlib/tools/items/ItemStackBuilder.java (hunk 1 above)
Comment (AmauryCarrade) [reply src/main/java/fr/zcraft/quartzlib/tools/items/ItemStackBuilder.java:684]: Okay, if we re-center the objective of this tool to be more generic than before, I'm fine with that.

**Review by AmauryCarrade — APPROVED** [review]
I approve, if we plan another PR with all MojangHead values tested.
